name: Generate Plugin Zip

on:
    workflow_dispatch:
        inputs:
            ref:
                description: 'Git Commit Ref (branch, tag, or hash)'
                required: false
                type: string


jobs:
    build:
        uses: impress-org/givewp-github-actions/.github/workflows/generate-zip.yml@master
        with:
            ref: ${{ github.event.inputs.ref }}
            plugin_slug: blocks-for-github
            install_composer_packages: false
